ProjectFiles/WCS/WCS/Models/DataModels/StudentRating.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace WCS.Models
{
    public class StudentRating
    {
        public int Id { get; set; }

        public int StudentProfileId { get; set; }
        [JsonIgnore]
        public StudentProfile StudentProfile { get; set; }

        public int AwardCycleId { get; set; }
        [JsonIgnore]
        public AwardCycle AwardCycle { get; set; }

        [ForeignKey("Judge")]
        public string JudgeId { get; set; }
        [JsonIgnore]
        public User Judge { get; set; }

        public int Rating { get; set; }
    }
}

ProjectFiles/WCS/WCS/Controllers/API/StudentRatingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WCS.Data;
using WCS.Models;

namespace WCS.Controllers
{
    [Produces("application/json")]
    [Route("api/StudentRatings")]
    public class StudentRatingsController : Controller
    {
        private readonly WcsContext _context;
        private readonly UserManager<User> _userManager;

        public StudentRatingsController(WcsContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: api/StudentRatings
        [HttpGet]
        public IEnumerable<StudentRating> GetStudentRatings()
        {
            return _context.StudentRatings;
        }

        // GET: api/StudentRatings/5
        [HttpGet("{id}")]
        public async Task<IActionResult> GetStudentRating([FromRoute] int id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var studentRating = await _context.StudentRatings.SingleOrDefaultAsync(m => m.Id == id);

            if (studentRating == null)
            {
                return NotFound();
            }

            return Ok(studentRating);
        }

        // PUT: api/StudentRatings/5
        //[HttpPut("{id}")]
        //public async Task<IActionResult> PutStudentRating([FromRoute] int id, [FromBody] StudentRating studentRating)
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        return BadRequest(ModelState);
        //    }

        //    if (id != studentRating.Id)
        //    {
        //        return BadRequest();
        //    }

        //    _context.Entry(studentRating).State = EntityState.Modified;

        //    try
        //    {
        //        await _context.SaveChangesAsync();
        //    }
        //    catch (DbUpdateConcurrencyException)
        //    {
        //        if (!StudentRatingExists(id))
        //        {
        //            return NotFound();
        //        }
        //        else
        //        {
        //            throw;
        //        }
        //    }

        //    return NoContent();
        //}

        // POST: api/StudentRatings
        [HttpPost]
        public async Task<IActionResult> PostStudentRating([FromBody] StudentRating studentRating)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            User currentJudge = await _userManager.GetUserAsync(User);
            int currentAwardCycleId = Assistant.GetCurrentAwardCycle(_context).Id;

            if (studentRating.Id == 0)
            {
                StudentRating original = await _context.StudentRatings.FirstOrDefaultAsync(r => r.StudentProfileId == studentRating.StudentProfileId &&
                    r.JudgeId == currentJudge.Id && r.AwardCycleId == currentAwardCycleId);

                if (original == null)
                {
                    studentRating.AwardCycleId = currentAwardCycleId;
                    studentRating.JudgeId = currentJudge.Id;
                    _context.StudentRatings.Add(studentRating);
                    await _context.SaveChangesAsync();
                    return Ok(studentRating.Id);
                }
                else
                {
                    original.Rating = studentRating.Rating;
                    await _context.SaveChangesAsync();
                    return Ok(original.Id);
                }
            }
            else if (_context.StudentRatings.Any(r => r.Id == studentRating.Id && r.JudgeId == currentJudge.Id && r.AwardCycleId == currentAwardCycleId))
            {
                _context.Entry(studentRating).State = EntityState.Modified;
                await _context.SaveChangesAsync();
                return Ok(studentRating.Id);
            }
            else
                return BadRequest("Couldn't verify this rating");
        }

        // DELETE: api/StudentRatings/5
        //[HttpDelete("{id}")]
        //public async Task<IActionResult> DeleteStudentRating([FromRoute] int id)
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        return BadRequest(ModelState);
        //    }

        //    var studentRating = await _context.StudentRatings.SingleOrDefaultAsync(m => m.Id == id);
        //    if (studentRating == null)
        //    {
        //        return NotFound();
        //    }

        //    _context.StudentRatings.Remove(studentRating);
        //    await _context.SaveChangesAsync();

        //    return Ok(studentRating);
        //}

        private bool StudentRatingExists(int id)
        {
            return _context.StudentRatings.Any(e => e.Id == id);
        }
    }
}

ProjectFiles/WCS/WCS/Controllers/AdminController.cs
/*
    We will create an AwardCycle to control open applications times. Archive is when a cycle has ended/closed.
        * ID, CycleName, OpenDate, CloseDate
    Use the Active flag to find the current cycle.
    We will create a Dispatch Timer on startup to check the status of the current cycle and check if we are starting the next cycle
    Dispatcher Job will set the AllowStudentLogin (in program.cs) to True when we are in current Active Award Cycle.

*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WCS.Data;
using WCS.Models;
using WCS.Services;

namespace WCS.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class AdminController : Controller
    {
        private readonly WcsContext _context;
        private readonly IEmailSender _emailSender;
        private readonly UserManager<User> _userManager;

        [TempData]
        public string StatusMessage { get; set; }

        public AdminController(WcsContext context, IEmailSender emailSender, UserManager<User> userManager)
        {
            _context = context;
            _emailSender = emailSender;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            AdminDashViewModel model = new AdminDashViewModel()
            {
                AwardCycles = await _context.AwardCycles.OrderByDescending(c => c.StartDate).Where(c => !c.Recycled).ToListAsync()
            };

            return View(model);
        }

        #region User Management
        public async Task<IActionResult> UserList()
        {
            List<User> users = await _context.Users.ToListAsync();
            foreach(User user in users)
            {
                user.Role = (await _userManager.GetRolesAsync(user)).First();
            }
            users.Sort();
            return View(users);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> EditUser(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.SingleOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditUser(string id, [Bind("FirstName,MiddleInitial,LastName,Id,Email, EmailConfirmed, Role")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //Update selected fields only (This avoids the DbUpdate Concurrency Exception)
                    User updatedUser = _context.Users.FirstOrDefault(u => u.Id == user.Id);
                    updatedUser.FirstName = user.FirstName;
                    updatedUser.LastName = user.LastName;
                    updatedUser.MiddleInitial = user.MiddleInitial;
                    updatedUser.Email = user.Email;
                    updatedUser.EmailConfirmed = user.EmailConfirmed;         

                    //Update
                    _context.Update(updatedUser);
                    await _context.SaveChangesAsync();

                    string role = (await _userManager.GetRolesAsync(updatedUser)).First();

                    if (!role.Equals(user.Role))
                    {
                        await _userManager.AddToRoleAsync(updatedUser, user.Role);
                        await _userManager.RemoveFromRoleAsync(updatedUser, role);
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(UserList));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> DeleteUser(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .SingleOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var user = await _context.Users.SingleOrDefaultAsync(m => m.Id == id);
            _context.Users.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(UserList));
        }

        private bool UserExists(string id)
        {
            return _context.Users.Any(e => e.Id == id);
        }
        #endregion

        #region Course Management
        public async Task<IActionResult> CourseList()
        {
            return View(await _context.Courses.ToListAsync());
        }

        // GET: Courses/Create
        public IActionResult CreateCourse()
        {
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateCourse([Bind("Id,CourseName,CourseNumber,ConcurrentCourse")] Course course)
        {
            if (ModelState.IsValid)
            {
                _context.Add(course);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(CourseList));
            }
            return View(course);
        }

        // GET: Courses/Edit/5
        public async Task<IActionResult> EditCourse(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses.SingleOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditCourse(int id, [Bind("Id,CourseName,CourseNumber,ConcurrentCourse")] Course course)
        {
            if (id != course.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(course);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseExists(course.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(CourseList));
            }
            return View(course);
        }

        // GET: Courses/Delete/5
        public async Task<IActionResult> DeleteCourse(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .SingleOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("DeleteCourse")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteCourseConfirmed(int id)
        {
            var course = await _context.Courses.SingleOrDefaultAsync(m => m.Id == id);
            _context.Courses.Remove(course);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(CourseList));
        }

        private bool CourseExists(int id)
        {
            return _context.Courses.Any(e => e.Id == id);
        }
        #endregion

        #region Award Cycle Management

        // GET: AwardCycles/Create
        public IActionResult CreateAwardCycle()
        {
            return View();
        }

        // POST: AwardCycles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateAwardCycle([Bind("Id,CycleName,StartDate,EndDate,Status")] AwardCycle awardCycle)
        {
            if (ModelState.IsValid)
            {
                _context.Add(awardCycle);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(awardCycle);
        }

        // GET: AwardCycles/Edit/5

ProjectFiles/WCS/WCS/Controllers/ScholarshipAwardsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WCS.Data;
using WCS.Models;
using Microsoft.AspNetCore.Authorization;

namespace WCS.Controllers
{
    [Authorize(Roles = "Administrator, Judge")]
    public class ScholarshipAwardsController : Controller
    {
        private readonly WcsContext _context;

        public ScholarshipAwardsController(WcsContext context)
        {
            _context = context;
        }

        // GET: ScholarshipAwards
        public async Task<IActionResult> Index()
        {
            ScholarshipAwardsViewModel model = new ScholarshipAwardsViewModel()
            {
                AwardCycle = Assistant.GetCurrentAwardCycle(_context),
                Scholarships = new ScholarshipCarrier(_context).Scholarships,
                AwardsListModel = new ScholarshipAwardsListModel(_context),
                StudentRatingsListPack = new StudentRatingsListPack(_context)
            };

            return View(model);
        }

        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> DeleteAward(int? id)
        {
            int currentCycleId = Assistant.GetCurrentAwardCycle(_context).Id;
            ScholarshipAward award = _context.ScholarshipAwards.Include(a => a.AwardMonies).FirstOrDefault(a => a.Id == id && a.AwardCycleId == currentCycleId);

            if (award == null)
                return NotFound("Award Not Found or Is not in the current Award Cycle");

            foreach (ScholarshipAwardMoney money in award.AwardMonies)
                _context.ScholarshipAwardMonies.Remove(money);

            _context.ScholarshipAwards.Remove(award);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

ProjectFiles/WCS/WCS/Views/Shared/_FormFieldPartial.cshtml
@using Newtonsoft.Json
@using WCS.Models

@model StudentResponsePack

<div class="form-field" id="@Model.FormField.Id">
    <input type="hidden" class="form-field-data" value="@JsonConvert.SerializeObject(Model.FormField)" />
    <input type="hidden" class="form-response-data" value="@JsonConvert.SerializeObject(Model.FormResponse)" />
    @if (Model.FormField.Required)
    {
        <span class="form-field-required">*</span>
    }
    <span class="form-field-title">@Model.FormField.Title</span>

    @switch (Model.FormField.Type)
    {
        case "Number Box":
            <input type="number" class="form-field-input form-input-number" id="@Model.FormField.Id" value="@Model.FormResponse.Response" />
            break;

        case "Text Box":
            <input type="text" class="form-field-input form-input-textbox" id="@Model.FormField.Id" value="@Model.FormResponse.Response" />
            break;

        case "Text Area":
            <div class="form-field-textarea">
                <textarea class="form-field-input form-input-textarea" id="@Model.FormField.Id">@Model.FormResponse.Response</textarea>
                @{
                    dynamic taoptions = JsonConvert.DeserializeObject(Model.FormField.Options);
                    string wordsmin;

                    if (taoptions.MinWords < 1)
                    {
                        wordsmin = "Any";
                    }
                    else
                    {
                        wordsmin = taoptions.MinWords;
                    }
                }
                <div class="form-field-wordcount"><span class="wordcount-label">Word Count: </span><span class="wordcount-count"></span>
                <span class="wordcount-min-label">Suggested: <span class="wordcount-min">@wordsmin</span></span></div>
            </div>
            break;

        case "Selection Box":
            <select class="form-field-input form-input-selectionbox" id="@Model.FormField.Id">
                <option>Make a Selection</option>
                @{
                    dynamic field = JsonConvert.DeserializeObject(Model.FormField.Options);

                    @foreach (string item in field.Items)
                    {

                        if (Model.FormResponse.Response == item)
                        {
                            <option selected="selected">@item</option>
                        }
                        else
                        {
                            <option>@item</option>
                        }

                    }
                }
            </select>
            break;
    }
    <span class="form-field-error"></span>
</div>

ProjectFiles/WCS/WCS/Views/Shared/_FormFieldReadOnly.cshtml
@using Newtonsoft.Json
@using WCS.Models
@model StudentResponsePack
<div class="form-field" id="@Model.FormField.Id">
    @if (Model.FormField.Required)
    {
        <span class="form-field-required">*</span>
    }
    <span class="form-field-title">@Model.FormField.Title</span>
    @switch (Model.FormField.Type)
    {
        case "Number Box":
            <input type="text" class="form-field-input form-input-number" id="@Model.FormField.Id" value="@Model.FormResponse.Response" readonly/>
            break;

        case "Text Box":
            <input type="text" class="form-field-input form-input-textbox" id="@Model.FormField.Id" value="@Model.FormResponse.Response" readonly/>
            break;

        case "Text Area":
            <div class="form-field-textarea">
                <textarea class="form-field-input form-input-textarea" id="@Model.FormField.Id" readonly>@Model.FormResponse.Response</textarea>
                @{
                    dynamic taoptions = JsonConvert.DeserializeObject(Model.FormField.Options);
                    string wordsmin;

                    if (taoptions.MinWords < 1)
                    {
                        wordsmin = "Any";
                    }
                    else
                    {
                        wordsmin = taoptions.MinWords;
                    }
                }
                <div class="form-field-wordcount">
                    <span class="wordcount-label">Word Count: </span><span class="wordcount-count"></span>
                    <span class="wordcount-min-label">Suggested: <span class="wordcount-min">@wordsmin</span></span>
                </div>
            </div>
            break;

        case "Selection Box":
            <select class="form-field-input form-input-selectionbox" id="@Model.FormField.Id" disabled>
                <option>Make a Selection</option>
                @{
                    dynamic field = JsonConvert.DeserializeObject(Model.FormField.Options);

                    @foreach (string item in field.Items)
                    {

                        if (Model.FormResponse.Response == item)
                        {
                            <option selected="selected">@item</option>
                        }
                        else
                        {
                            <option>@item</option>
                        }

                    }
                }
            </select>
            break;
    }
    <span class="form-field-error"></span>
</div>

ProjectFiles/WCS/WCS/Views/Shared/_FormForJudging.cshtml
@model StudentFormPack
@using WCS.Models
@using Newtonsoft.Json

<div class="form">
    <section>
        <div class="form-ratings-title">Application Ratings</div>
        @foreach (StudentRatingPack ratingpack in Model.StudentRatingPacks)
        {
            <div class="form-rating" id="@JsonConvert.SerializeObject(ratingpack)"></div>
        }
    </section>
    <hr/>
    <section>
        <div class="form-ratings-title">Application Responses</div>
        @foreach (StudentResponsePack responsepack in Model.StudentResponsePacks)
        {
            @Html.Partial("_FormFieldReadOnly", responsepack)
        }
    </section>
</div>

ProjectFiles/WCS/WCS/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using WCS.Models
@inject UserManager<User> UserManager
@inject SignInManager<User> SignInManager
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=0.7" />
    <title>@ViewData["Title"] - WCS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery/dist/jquery-ui.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body>
    <div class="weberHeader">
        <div class="container">
            <img src="~/images/wsu-logo-wcs.svg" alt="Weber State University Logo" class="weberLogo" />
        </div>
    </div>
    <nav class="navbar weberNavBar">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @* This Home will always redirect the user to their dashboard page if they are logged in. *@
                @*<a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">WCS</a>*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @{
                        if (SignInManager.IsSignedIn(User))
                        {
                            var user = await UserManager.GetUserAsync(User);
                            if (await UserManager.IsInRoleAsync(user, "Student"))
                            {
                                <li><a asp-area="" asp-controller="Student" asp-action="Index" title="Apply for Scholarships">Scholarships</a></li>
                                <li><a asp-area="" asp-controller="Student" asp-action="EditStudentProfile">Profile Information</a></li>
                            }
                            if (await UserManager.IsInRoleAsync(user, "Judge"))
                            {
                                <li><a asp-area="" asp-controller="Judge" asp-action="Index" title="View/Rate Student Applications">Applications</a></li>
                                <li><a asp-area="" asp-controller="ScholarshipAwards" asp-action="Index" title="View Scholarship Awards">Awards</a></li>
                            }
                            if (await UserManager.IsInRoleAsync(user, "Administrator"))
                            {
                                <li><a asp-area="" asp-controller="Admin" asp-action="Index" title="Perform Administrator Actions">Admin Dashboard</a></li>
                                <li><a asp-area="" asp-controller="Judge" asp-action="Index" title="View/Rate Student Applications">Applications</a></li>
                                <li><a asp-area="" asp-controller="ScholarshipAwards" asp-action="Index" title="Manage Scholarship Awards">Awards</a></li>
                            }
                        }
                        else
                        {
                            <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        }
                    }
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
    </div>
    @RenderSection("Scripts", required: false)
</body>
</html>

ProjectFiles/WCS/WCS/Views/Shared/_ScholarshipAwardsList.cshtml
@model WCS.Models.ScholarshipAwardsListModel
@using WCS.Models
@if (Model.AllowEdit)
{
    @inject UserManager<User> userManager
    User currentUser = await userManager.GetUserAsync(User);
    Model.AllowEdit = await userManager.IsInRoleAsync(currentUser, "Administrator");
}

<div class="list-awards">
    <table class="table table-list table-list-awards">
        <caption>
            Scholarship Awards
            @if (Model.AllowEdit)
            {
                <button class="list-btn-new list-btn-caption" onclick="initAwardEditor()">Award a Scholarship</button>
            }
        </caption>
        <thead>
            <tr>
                <th>
                    Date
                </th>
                <th>
                    Scholarship Name
                </th>
                <th>
                    Student Name
                </th>
                <th>
                    Total Award
                </th>
                @if (Model.AllowEdit)
                {
                    <th></th>
                }
            </tr>
        </thead>
        <tbody>
            @foreach (var award in Model.Awards)
            {
                string even = "";
                if (Model.Awards.IndexOf(award) % 2 != 0)
                {
                    even = "even";
                }
                <tr class="award-row-scholarship @even" id="@award.Id" title="Click to toggle funding sources">
                    <td>
                        @Html.DisplayFor(i => award.DateAwarded)
                    </td>
                    <td>
                        @Html.DisplayFor(i => award.Scholarship.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(i => award.StudentProfile.FullName)
                    </td>
                    <td>
                        $ @Html.DisplayFor(i => award.TotalAwardMoney)
                    </td>
                    @if (Model.AllowEdit)
                    {
                        <td class="notrow" title="Admin Functions">
                            <img src="~/images/form/edit.svg" id="@award.StudentProfileId" class="btn-award btn-award-edit" title="Edit this award" />
                            <img src="~/images/form/cancel.svg" id="@award.Id" class="btn-award btn-award-remove" title="remove this award" />
                        </td>
                    }
                </tr>

                @foreach (var money in award.AwardMonies)
                {
                    <tr class="award-row-funding" id="@award.Id" style="display: none;">
                        <td></td>
                        <td colspan="2" class="fundbox">
                            @Html.DisplayFor(i => money.ScholarshipFund.Name)
                        </td>
                        <td>
                            $ @Html.DisplayFor(i => money.Amount)
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>
<link rel="stylesheet" href="~/css/wcs.scholarshipawards.css" />
<script type="text/javascript">
    $(document).ready(function (event) {
        $(".award-row-scholarship").click(function () {
            $("#" + $(this).attr("id") + ".award-row-funding").fadeToggle(1);
        });

        $(".notrow").click(function (event) {
            event.stopPropagation();
        });
    });
</script>