ProjectFiles/WCS/WCS/Models/JudgeViewModels/JudgeByStudentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WCS.Models
{
    public class JudgeByStudentViewModel
    {
        public AwardCycle AwardCycle { get; set; }

        public List<StudentPack> StudentPacks { get; set; }
    }
}

ProjectFiles/WCS/WCS/Controllers/JudgeController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WCS.Data;
using WCS.Models;

namespace WCS.Controllers
{
    [Authorize(Roles = "Judge,Administrator")]
    public class JudgeController : Controller
    {
        private readonly WcsContext _context;
        private readonly UserManager<User> _userManager;

        public JudgeController(WcsContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return RedirectToAction(nameof(JudgeByStudent));
        }

        /// <summary>
        /// Judge all student applications grouped by student
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> JudgeByStudent()
        {
            User currentJudge = await _userManager.GetUserAsync(User);
            AwardCycle currentCycle = Assistant.GetCurrentAwardCycle(_context);
            int currentAwardCycleId = currentCycle.Id;
            List<StudentForm> currentStudentForms = _context.StudentForms
                .Include(s => s.StudentProfile)
                .Include(s => s.Form)
                .Include(s => s.FormRatings)
                .Where(f => f.AwardCycleId == currentAwardCycleId).ToList();

            if (currentStudentForms == null || currentStudentForms.Count == 0)
            {
                return RedirectToAction(nameof(NoApplications));
            }
            List<ScholarshipAward> allAwards = await _context.ScholarshipAwards.Include(a => a.Scholarship).Include(a => a.AwardMonies).ToListAsync();
            List<StudentRating> allStudentRatings = await _context.StudentRatings
                .Where(r => r.JudgeId == currentJudge.Id && r.AwardCycleId == currentAwardCycleId).ToListAsync();
            List<StudentCourse> allStudentCourses = await _context.StudentCourses.Include(c => c.Course).ToListAsync();
            List<StudentPack> studentPacks = new List<StudentPack>();
            List<int> packed = new List<int>();
            foreach (StudentForm studentForm in currentStudentForms)
            {
                if (!packed.Contains(studentForm.StudentProfileId))
                {
                    studentForm.StudentProfile.ScholarshipAwards = allAwards.Where(a => a.StudentProfileId == studentForm.StudentProfileId).ToList();
                    studentForm.StudentProfile.StudentCourses =
                        from c in allStudentCourses
                        where c.StudentId == studentForm.StudentProfileId
                        select c.Course.CourseNumber;
                    packed.Add(studentForm.StudentProfileId);
                    studentPacks.Add(new StudentPack(studentForm.StudentProfile,
                        allStudentRatings.FirstOrDefault(r => r.StudentProfileId == studentForm.StudentProfileId),
                        currentStudentForms.Where(f => f.StudentProfileId == studentForm.StudentProfileId).ToList(),
                        currentJudge.Id, _context));
                }
            }

            studentPacks.Sort();

            JudgeByStudentViewModel model = new JudgeByStudentViewModel
            {
                AwardCycle = currentCycle,
                StudentPacks = studentPacks
            };

            return View(model);
        }

        /// <summary>
        /// Judge all students for one form
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> JudgeByForm(int? id)
        {

            User currentJudge = await _userManager.GetUserAsync(User);

            AwardCycle currentCycle = Assistant.GetCurrentAwardCycle(_context);
            int currentAwardCycleId = currentCycle.Id;

            JudgeByFormViewModel model = new JudgeByFormViewModel() {
                AwardCycle = currentCycle,
                FormPacks = new List<FormPack>()
            };

            List<StudentRating> allStudentRatings = await _context.StudentRatings
                .Where(r => r.JudgeId == currentJudge.Id && r.AwardCycleId == currentAwardCycleId).ToListAsync();

            List<StudentCourse> allStudentCourses = await _context.StudentCourses.Include(c => c.Course).ToListAsync();

            List<StudentForm> currentStudentForms = _context.StudentForms
                .Include(s => s.StudentProfile)
                .Include(s => s.Form)
                .Include(s => s.FormRatings)
                .Where(f => f.AwardCycleId == currentAwardCycleId).ToList();

            //Form filter
            if (currentStudentForms == null || currentStudentForms.Count == 0)
            {
                return RedirectToAction(nameof(NoApplications));
            }

            model.SelectedFormId = id ?? currentStudentForms[0].FormId;

            foreach (Form form in _context.Forms.OrderBy(f => f.Title).Include(f => f.FormCriteria).Where(f => f.Active))
            {
                List<StudentForm> applications = currentStudentForms.Where(f => f.FormId == form.Id).ToList();

                FormPack newPack = new FormPack()
                {
                    Form = form,
                    AppliedCount = applications.Count,
                    RatedCount = 0
                };

                //count ratings
                foreach (StudentForm app in applications)
                {
                    if (app.FormRatings.Count(r => r.JudgeId == currentJudge.Id) >= form.FormCriteria.Count &&
                            allStudentRatings.Any(r => r.StudentProfileId == app.StudentProfileId))
                        newPack.RatedCount++;
                }

                if (form.Id == model.SelectedFormId)
                    model.SelectedForm = newPack;
                else
                    model.FormPacks.Add(newPack);
            }

            //Filter applications by form
            currentStudentForms = currentStudentForms.Where(f => f.FormId == model.SelectedFormId).ToList();
            List<ScholarshipAward> allAwards = await _context.ScholarshipAwards.Include(a => a.Scholarship).Include(a => a.AwardMonies).ToListAsync();
            List<StudentPack> studentPacks = new List<StudentPack>();
            List<int> packed = new List<int>();
            foreach (StudentForm studentForm in currentStudentForms)
            {
                if (!packed.Contains(studentForm.StudentProfileId))
                {
                    studentForm.StudentProfile.ScholarshipAwards = allAwards.Where(a => a.StudentProfileId == studentForm.StudentProfileId).ToList();
                    studentForm.StudentProfile.StudentCourses =
                        from c in allStudentCourses
                        where c.StudentId == studentForm.StudentProfileId
                        select c.Course.CourseNumber;
                    packed.Add(studentForm.StudentProfileId);
                    studentPacks.Add(new StudentPack(studentForm.StudentProfile,
                        allStudentRatings.FirstOrDefault(r => r.StudentProfileId == studentForm.StudentProfileId),
                        currentStudentForms.Where(f => f.StudentProfileId == studentForm.StudentProfileId).ToList(),
                        currentJudge.Id, _context));
                }
            }

            studentPacks.Sort();
            model.StudentPacks = studentPacks;

            return View(model);
        }

        public IActionResult NoApplications()
        {
            return View();
        }
    }
}

ProjectFiles/WCS/WCS/Views/Judge/JudgeByForm.cshtml
@model JudgeByFormViewModel
@using WCS.Models
@using Newtonsoft.Json
@{
    ViewData["Title"] = "WCS - Judge By Form";
}
<div class="row">
    <div class="col-md-9 judge-cycle-header">
        <div class="judge-cycle-inner clearfix">
            <span class="award-cycle-name">@Model.AwardCycle.CycleName</span>
            [ @Html.DisplayFor(i => Model.AwardCycle.StartDate) to @Html.DisplayFor(i => Model.AwardCycle.EndDate) ]
        </div>
    </div>
    <div class="col-md-3 judge-cycle-header">
        <div class="award-btn judge-btn" title="Click to toggle rating style" onclick="switchMethod()">
            Students <img class="img-judge-swap" src="~/images/swap_right.svg" /> <span class="judge-btn-selected">Forms</span>
        </div>
    </div>
    <div class="col-md-5 judge-list-container">
        <div class="judge-list-header clearfix">
            <img class="judge-list-expander" src="~/images/enlarge.svg" />
            <select class="form-links-select" id="formlinks" onchange="navigate()" title="Change Form For Judging">
                @if (Model.SelectedForm != null)
                {
                    <option>@Model.SelectedForm.Form.Title</option>
                }
                @foreach (FormPack formPack in Model.FormPacks)
                {
                    string action = "JudgeByForm/" + formPack.Form.Id;
                    <option value="@Url.Action(action, "Judge")">
                        (@formPack.RatedCount/@formPack.AppliedCount) @formPack.Form.Title
                    </option>
                }
            </select><button class="btn btn-primary judge-list-button-toggle" data-toggle="button" id="filterStudents" title="Toggle Unrated Only View">Unrated <small id="allUnrated" style="color: yellow; margin-left: 5px;">0 / 0</small></button>
        </div>
        @await Html.PartialAsync("_StudentList", Model.StudentPacks)
    </div>
    <div class="col-md-7 judge-view-container">
        <div class="judge-view-inner">
            @foreach (StudentPack studentPack in Model.StudentPacks)
            {
                @if (studentPack.Student != null && studentPack.TotalApplicationsCount > 0)
                {
                    string packId = "studentpack" + studentPack.Student.Id;
                    <div class="student-pack" id="@packId">
                        <div class="student-profile-container">
                            <div class="student-pack-title">@studentPack.Student.FullName</div>
                            @await Html.PartialAsync("_StudentProfile", studentPack.Student)
                            <div class="student-rating" id="@JsonConvert.SerializeObject(studentPack.StudentRating)"></div>
                        </div>
                        @foreach (StudentFormPack pack in studentPack.StudentFormPacks)
                        {
                            string panelId = "form" + pack.StudentForm.Id;
                            string ratedClass = "";
                            if (pack.IsRatedFull) { ratedClass = "form-rated"; }
                            <div class="panel panel-default form-container @ratedClass">
                                <div id="@panelId">
                                    @await Html.PartialAsync("_FormForJudging", pack)
                                </div>
                            </div>
                        }
                    </div>
                }
            }
        </div>
    </div>
</div>
<script src="~/js/wcs.judging.js" asp-append-version="true"></script>
<script src="~/js/wcs.judgebyform.js" asp-append-version="true"></script>
<script type="text/javascript">
    function switchMethod() {
        location.href = "/Judge/JudgeByStudent";
    }
</script>

ProjectFiles/WCS/WCS/Views/Judge/JudgeByStudent.cshtml
@model JudgeByStudentViewModel
@using WCS.Models
@using Newtonsoft.Json
@{
    ViewData["Title"] = "WCS - Judge By Student";
}
<div class="row">
    <div class="col-lg-9 judge-cycle-header">
        <div class="judge-cycle-inner clearfix">
            <span class="award-cycle-name">@Model.AwardCycle.CycleName</span>
            [ @Html.DisplayFor(i => Model.AwardCycle.StartDate) to @Html.DisplayFor(i => Model.AwardCycle.EndDate) ]
        </div>
    </div>
    <div class="col-lg-3 judge-cycle-header">
        <div class="award-btn judge-btn" title="Click to toggle rating style" onclick="switchMethod()">
            <span class="judge-btn-selected">Students</span> <img class="img-judge-swap" src="~/images/swap_left.svg" /> Forms
        </div>
    </div>
    <div class="col-md-5 judge-list-container">
        <div class="judge-list-header clearfix">
            <img class="judge-list-expander" src="~/images/enlarge.svg" /><span class="judge-list-title">Students</span>
            <button class="btn btn-primary judge-list-button-toggle" data-toggle="button" id="filterStudents" title="Toggle Unrated Only View">Unrated <small id="allUnrated" style="color: yellow; margin-left: 5px;">0 / 0</small></button>
        </div>
        @await Html.PartialAsync("_StudentList", Model.StudentPacks)
    </div>
    <div class="col-md-7 judge-view-container">
        <div class="judge-view-inner">
            @foreach (StudentPack studentPack in Model.StudentPacks)
            {
                @if (studentPack.Student != null && studentPack.TotalApplicationsCount > 0)
                {
                    string packId = "studentpack" + studentPack.Student.Id;
                    <div class="student-pack" id="@packId">
                        <div class="student-profile-container">
                            <div class="student-pack-title">@studentPack.Student.FullName</div>
                            @await Html.PartialAsync("_StudentProfile", studentPack.Student)
                            <div class="student-rating" id="@JsonConvert.SerializeObject(studentPack.StudentRating)"></div>
                        </div>
                        @{ string accordionId = "accordion" + studentPack.Student.Id;}
                        <div class="panel-group" id="@accordionId" role="tablist" aria-multiselectable="true">
                            @foreach (StudentFormPack pack in studentPack.StudentFormPacks)
                            {
                                string panelId = "form" + pack.StudentForm.Id;
                                string ratedClass = "";
                                if (pack.IsRatedFull) { ratedClass = "form-rated"; }
                                <div class="panel panel-default form-container @ratedClass">
                                    <div class="accordion-header collapsed panel-heading clearfix form-title-container" role="tab" data-toggle="collapse"
                                         data-target="#@panelId" aria-controls="@panelId" data-parent="#@accordionId">
                                        @{ string ratedText;}
                                        @if (pack.IsRatedFull)
                                        {
                                            ratedText = "You have rated this application";
                                            <img class="form-title-icon" src="~/images/shield_green.svg" />
                                        }
                                        else if (pack.IsRatedPartial)
                                        {
                                            ratedText = "You have partially rated this application";
                                            <img class="form-title-icon" src="~/images/shield_orange.svg" />
                                        }
                                        else
                                        {
                                            ratedText = "You have not rated this application";
                                            <img class="form-title-icon" src="~/images/shield_red.svg" />
                                        }
                                        <span class="form-title panel-title">
                                            @Html.Raw(pack.Form.Title)
                                        </span><br /><span class="form-title-rated">@ratedText</span>
                                    </div>
                                    <div class="panel-collapse collapse accordion-container" role="tabpanel" id="@panelId">
                                        @await Html.PartialAsync("_FormForJudging", pack)
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                }
            }
        </div>
    </div>
</div>

<script src="~/js/wcs.judging.js" asp-append-version="true"></script>
<script src="~/js/wcs.judgebystudent.js" asp-append-version="true"></script>
<script type="text/javascript">
    function switchMethod() {
        location.href = "/Judge/JudgeByForm";
    }
</script>

ProjectFiles/WCS/WCS/Views/Judge/NoApplications.cshtml
@{
    ViewData["Title"] = "No Applications to Judge";
}

<h2>There are no applications for the current award cycle.</h2>